version: "3"

services:
   project:
      image: youtube_shorts_downloader
      container_name: youtube_shorts_downloader_c
      build: .
      command: python3 ./main.py
      volumes:
         - .:/app
      env_file: .env
