# Generated by Django 3.2.9 on 2021-11-15 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 57, 44, 563580)),
        ),
    ]
